//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.10.31 at 10:35:19 PM ICT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "www.kimthanh.com/schema/listCategory", 
                                    elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED,
                                    xmlns={@XmlNs(prefix="cate",
                                            namespaceURI="www.kimthanh.com/schema/category")})
package sample.jaxb.category;

import javax.xml.bind.annotation.XmlNs;

